---
title: "Research topics"
author: "Tim Le, Sophie Xu"
format: pdf
---

# Topic 1

1.  A brief description of the topic

**We want to see how different demographic variables affect a powerlifter’s performance, placement, and weight of lifts in different USPA competitions.**

2.  A statement about your motivation for investigating this topic

**Both of us are interested in weightlifting fitness.**

3.  The potential audience(s), i.e., who might be most interested in this research?

**People who would be interested in our research include USPA powerlifting athletes, anyone interested in powerlifting statistics, and anyone interested in fitness.**\

4.  Two or three potential research questions you could analyze about this topic. (Note: These are draft questions at this point. You will finalize the questions in the next stage of the project.)

**Given a powerlifter’s body weight, can we predict their top lifts in the squat, bench press, and deadlift? How correlated are these variables?**

**Given a powerlifter’s height, can we predict their top lifts in the squat, bench press, and deadlift. What about their placement in the competition? How correlated are these variables?**

**Given a powerlifter’s ethnicity, can we predict their top lifts in the squat, bench press, and deadlift? What about their placement in the competition?**

**In powerlifting competitions, the total weights for a lifter’s respective squat, bench press, and deadlift are totaled. What is the most common ratio of weight (squat : bench press : deadlift)? What ratio correlates to placement in the competition?**

5.  Ideas about the type of data you might use to answer this question or potential data sets you’re interested in using. (Note: The goal is to generate ideas at this point, so it is fine if you have not identified any particular data sets at this point.)

**We would use a dataset straight from the United States Powerlifting Association that contains information about everyone registered: bodyweight, height, maxes in the three lifts (squat, bench press, deadlift), where they are from, date of application, etc.**

# Topic 2

1.  A brief description of the topic

**We want to predict how much money college students make the first year out of undergrad, given data about their college activities.**

2.  A statement about your motivation for investigating this topic

**We are both college students. So many peers are concerned about their salary and first job after college, so we want to investigate which college activities impact their first job the most.**\

3.  The potential audience(s), i.e., who might be most interested in this research?

**Current and future college students needing advice, company recruiters.** \

4.  Two or three potential research questions you could analyze about this topic. (Note: These are draft questions at this point. You will finalize the questions in the next stage of the project.)

**How correlated is the number of clubs a college student is in with their first-year salary post-grad?**

**How correlated is the major of a college student to their first year of salary post-grad?**

**How correlated are a college student’s sleep habits with their first year of salary post-grad?**

5.  Ideas about the type of data you might use to answer this question or potential data sets you’re interested in using. (Note: The goal is to generate ideas at this point, so it is fine if you have not identified any particular data sets at this point.

**We need survey data on post-grad college students. This survey data should contain basic demographics, how much money they make the first year out of undergrad, their office position, and college activities, including: number of clubs they were in, number of courses taken, GPA, number of hours studying every day, number of hours of sleep, etc.**

# Topic 3

1.  A brief description of the topic

**We are interested in the characteristics of viral videos, the data/time it was published, the hashtags, the length of the video, and the account's current followers.**

2.  A statement about your motivation for investigating this topic

**TikTok is so influential in our everyday lives, and we want to know how this algorithm works.**

3.  The potential audience(s), i.e., who might be most interested in this research?

**Every day, TikTok viewers, content creators, and people who are interested in becoming influencers.**

4.  Two or three potential research questions you could analyze about this topic. (Note: These are draft questions at this point. You will finalize the questions in the next stage of the project.)

**How correlated is the video's length in time with the number of views it gets? In the first hour? In a day? Etc.**

**How correlated is the time of the post to the number of views it gets? In the first hour? In a day? Etc.**

**How correlated is the number of people featured in the video to the number of views it gets? In the first hour? In a day? Etc.**

5.  Ideas about the type of data you might use to answer this question or potential data sets you’re interested in using. (Note: The goal is to generate ideas at this point, so it is fine if you have not identified any particular data sets at this point.)

**We need a dataset of TikTok videos that contains information on various TikTok videos, including the data/time it was published, the hashtags, the length of the video, and the account's current followers.**
